/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 92a3c35aa7f220c3d1d331659f196ff9)
interface __BaseEnv_Env {
	KV: KVNamespace;
	ASSETS: Fetcher;
	CHANNELS: DurableObjectNamespace<import("./src/index").ChatRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ChatRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
